### ISSUE TITLE
Issue with Big 5 combined

### ISSUE THREAD

**Issue by andrewyimingchen** [oseymour/ScraperFC#23]
Hi, 

First of all, I just want to say thanks for creating this for scraping process a lot easier, Legend already. 

I have issue when using scrape_all_stats function, only 'Big 5 combined' return error message
Traceback (most recent call last):
  File "/var/folders/t0/_dnb2pb97vd4xlm44j304kv40000gn/T/ipykernel_44021/1658210061.py", line 5, in <module>
    lg_table_2022 = scraper.scrape_all_stats(year=2023, league='Big 5 combined')
  File "/Users/andrewchen/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/ScraperFC/FBRef.py", line 360, in scrape_all_stats
    stats = self.scrape_stats(year, league, stat_category, normalize)
  File "/Users/andrewchen/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/ScraperFC/FBRef.py", line 299, in scrape_stats
    (~squad_stats[('Unnamed: 0_level_0','Squad')].isna())
TypeError: 'NoneType' object is not subscriptable

Thanks,

Andrew

**Comment by oseymour** [comment]
Hey @andrewyimingchen! I'll check this out when I get a chance.

**Comment by oseymour** [comment]
@andrewyimingchen this should be fixed in the most recent commits and in v2.7.0 on PyPI. Please re-open this if it's not fixed on your end! Thank you!
